@extends('layouts.app')
@section('title', 'Trips worth taking')
@section('content')
<section class="hero"><div class="container-xl"><div class="hero-content">
    <span class="hero-stamp"><i class="bi bi-geo-alt-fill me-1"></i> San Carlos City, Pangasinan</span>
    <h1 class="mt-3 mb-3">Go further.<br>Come back with stories.</h1>
    <p>Thoughtfully planned tours, friendly local guidance, and the little details that make a trip feel like yours.</p>
    <a class="btn btn-coral mt-2" href="{{ route('packages.index') }}">Explore tour packages <i class="bi bi-arrow-up-right ms-1"></i></a>
</div></div></section>

<section class="section-pad"><div class="container-xl">
    <div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><span class="eyebrow">A good place to start</span><h2 class="section-heading mt-2 mb-0">Find the trip that fits your kind of curious.</h2></div><a class="btn btn-outline-forest" href="{{ route('packages.index') }}">All tour packages <i class="bi bi-arrow-right ms-1"></i></a></div>
    <div class="row g-4">@forelse($featuredPackages as $package)<div class="col-md-6 col-xl-4"><article class="package-card">
        <img class="package-image" src="{{ $package->image_path ? rtrim(config('services.supabase.url'), '/').'/storage/v1/object/public/'.config('services.supabase.buckets.tour_packages').'/'.$package->image_path : 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1000&q=80' }}" alt="{{ $package->name }}" loading="lazy">
        <div class="package-body"><div class="d-flex justify-content-between gap-3"><div><div class="package-meta"><i class="bi bi-geo-alt me-1"></i>{{ $package->destination->name }} · {{ $package->duration_days }} days</div><h3 class="h5 mt-2">{{ $package->name }}</h3></div><div class="package-price">₱{{ number_format((float) $package->price_per_person) }}</div></div><a class="btn btn-sm btn-outline-forest mt-3" href="{{ route('packages.show', $package) }}">View trip <i class="bi bi-arrow-up-right ms-1"></i></a></div>
    </article></div>@empty<div class="col-12"><div class="card-clean p-4 text-muted-custom">New journeys are being planned. Check back soon.</div></div>@endforelse</div>
</div></section>

<section class="section-pad pt-0"><div class="container-xl"><div class="row g-4 align-items-end mb-4"><div class="col"><span class="eyebrow">Places to remember</span><h2 class="section-heading mt-2 mb-0">A little farther from the everyday.</h2></div><div class="col-auto"><a href="{{ route('destinations.index') }}">Browse destinations <i class="bi bi-arrow-right"></i></a></div></div>
    <div class="row g-3">@forelse($destinations as $destination)<div class="col-sm-6 col-lg-4"><a class="destination-tile text-decoration-none" style="background-image:linear-gradient(0deg,rgba(12,34,31,.8),rgba(12,34,31,.08)),url('{{ $destination->image_path ? rtrim(config('services.supabase.url'), '/').'/storage/v1/object/public/'.config('services.supabase.buckets.destinations').'/'.$destination->image_path : 'https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=900&q=80' }}');background-size:cover;background-position:center" href="{{ route('packages.index', ['destination' => $destination->id]) }}"><div><h3 class="mb-1 text-white">{{ $destination->name }}</h3><span class="text-white-50">{{ $destination->tour_packages_count }} {{ Str::plural('tour', $destination->tour_packages_count) }}</span></div></a></div>@empty<div class="col-12 text-muted-custom">Discoveries are on the way.</div>@endforelse</div>
</div></section>

<section class="feature-band section-pad"><div class="container-xl"><div class="row g-5"><div class="col-lg-5"><span class="eyebrow">Why travel with us</span><h2 class="section-heading mt-2">Good trips start before you leave.</h2><p class="text-white-50">Local know-how, clear details, and a real team looking after your plans from the first click to the trip home.</p></div><div class="col-lg-7"><div class="row g-4"><div class="col-sm-6"><div class="feature-item"><i class="bi bi-signpost-split"></i><h3 class="h5 mt-3">Thoughtful routes</h3><p class="text-white-50 mb-0">Well-paced itineraries built around the places, not just the checklist.</p></div></div><div class="col-sm-6"><div class="feature-item"><i class="bi bi-chat-heart"></i><h3 class="h5 mt-3">People close by</h3><p class="text-white-50 mb-0">A local team you can reach when you need a hand with your plans.</p></div></div><div class="col-sm-6"><div class="feature-item"><i class="bi bi-receipt"></i><h3 class="h5 mt-3">Clear from day one</h3><p class="text-white-50 mb-0">Straightforward package details, inclusions, payment records, and trip updates.</p></div></div><div class="col-sm-6"><div class="feature-item"><i class="bi bi-shield-check"></i><h3 class="h5 mt-3">Bookings you can track</h3><p class="text-white-50 mb-0">Your reservation and payment status stay together in one account.</p></div></div></div></div></div></div></section>

<section class="section-pad"><div class="container-xl row g-4 align-items-center mx-auto"><div class="col-lg-7"><span class="eyebrow">Three easy steps</span><h2 class="section-heading mt-2">From browsing to boarding.</h2></div><div class="col-lg-5"><div class="d-flex gap-3 mb-3"><span class="brand-mark flex-shrink-0">1</span><div><strong>Pick your package</strong><div class="text-muted-custom">Compare the itinerary, dates, and available seats.</div></div></div><div class="d-flex gap-3 mb-3"><span class="brand-mark flex-shrink-0">2</span><div><strong>Reserve your group</strong><div class="text-muted-custom">Add traveler details and review your booking.</div></div></div><div class="d-flex gap-3"><span class="brand-mark flex-shrink-0">3</span><div><strong>Pay and get ready</strong><div class="text-muted-custom">Submit payment proof and track confirmation online.</div></div></div></div></div></section>
@endsection