@extends('layouts.app')
@section('title', $package->exists ? 'Edit package' : 'Create package')
@section('content')
<section class="page-header"><div class="container-xl"><span class="eyebrow">Tour management</span><h1 class="display-type mt-2">{{ $package->exists ? 'Edit package' : 'Create a tour package' }}</h1></div></section><section class="py-4"><div class="container-xl"><form class="card-clean p-3 p-lg-4" method="POST" enctype="multipart/form-data" action="{{ $package->exists ? route('staff.packages.update', $package) : route('staff.packages.store') }}">@csrf @if($package->exists)@method('PUT')@endif<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="name">Package name</label><input class="form-control" id="name" name="name" value="{{ old('name', $package->name) }}" required></div><div class="col-md-6"><label class="form-label" for="slug">Slug <span class="text-muted-custom">(optional)</span></label><input class="form-control" id="slug" name="slug" value="{{ old('slug', $package->slug) }}"></div>
    <div class="col-md-6"><label class="form-label" for="destination_id">Destination</label><select class="form-select" id="destination_id" name="destination_id" required><option value="">Select a destination</option>@foreach($destinations as $destination)<option value="{{ $destination->id }}" @selected(old('destination_id', $package->destination_id) == $destination->id)>{{ $destination->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label" for="status">Status</label><select class="form-select" id="status" name="status" required>@foreach(['draft','published','closed','archived'] as $status)<option value="{{ $status }}" @selected(old('status', $package->status ?: 'draft') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div>
    <div class="col-12"><label class="form-label" for="description">Description</label><textarea class="form-control" id="description" name="description" rows="4" required>{{ old('description', $package->description) }}</textarea></div>
    <div class="col-sm-4"><label class="form-label" for="duration_days">Days</label><input class="form-control" id="duration_days" name="duration_days" type="number" min="1" max="60" value="{{ old('duration_days', $package->duration_days ?: 1) }}" required></div><div class="col-sm-4"><label class="form-label" for="duration_nights">Nights</label><input class="form-control" id="duration_nights" name="duration_nights" type="number" min="0" max="59" value="{{ old('duration_nights', $package->duration_nights ?? 0) }}" required></div><div class="col-sm-4"><label class="form-label" for="price_per_person">Price per person (₱)</label><input class="form-control" id="price_per_person" name="price_per_person" type="number" min="0.01" step="0.01" value="{{ old('price_per_person', $package->price_per_person) }}" required></div>
    <div class="col-sm-4"><label class="form-label" for="maximum_capacity">Maximum capacity</label><input class="form-control" id="maximum_capacity" name="maximum_capacity" type="number" min="1" max="500" value="{{ old('maximum_capacity', $package->maximum_capacity ?: 20) }}" required></div><div class="col-sm-4"><label class="form-label" for="start_date">Start date</label><input class="form-control" id="start_date" name="start_date" type="date" value="{{ old('start_date', $package->start_date?->toDateString()) }}"></div><div class="col-sm-4"><label class="form-label" for="end_date">End date</label><input class="form-control" id="end_date" name="end_date" type="date" value="{{ old('end_date', $package->end_date?->toDateString()) }}"></div>
    <div class="col-md-6"><label class="form-label" for="booking_deadline">Booking deadline</label><input class="form-control" id="booking_deadline" name="booking_deadline" type="date" value="{{ old('booking_deadline', $package->booking_deadline?->toDateString()) }}"></div><div class="col-md-6"><label class="form-label" for="transportation">Transportation</label><input class="form-control" id="transportation" name="transportation" value="{{ old('transportation', $package->transportation) }}"></div>
    <div class="col-md-6"><label class="form-label" for="accommodation">Accommodation</label><input class="form-control" id="accommodation" name="accommodation" value="{{ old('accommodation', $package->accommodation) }}"></div><div class="col-md-6"><label class="form-label" for="meals">Meals</label><input class="form-control" id="meals" name="meals" value="{{ old('meals', $package->meals) }}"></div><div class="col-12"><label class="form-label" for="tour_guide">Tour guide information</label><textarea class="form-control" id="tour_guide" name="tour_guide" rows="2">{{ old('tour_guide', $package->tour_guide) }}</textarea></div>
    <div class="col-md-6"><label class="form-label" for="inclusions">Inclusions</label><textarea class="form-control" id="inclusions" name="inclusions" rows="4" placeholder="One item per line">{{ old('inclusions', implode("\n", $package->inclusions ?? [])) }}</textarea></div><div class="col-md-6"><label class="form-label" for="exclusions">Exclusions</label><textarea class="form-control" id="exclusions" name="exclusions" rows="4" placeholder="One item per line">{{ old('exclusions', implode("\n", $package->exclusions ?? [])) }}</textarea></div>
    <div class="col-12"><label class="form-label" for="image">Package image</label><input class="form-control" type="file" id="image" name="image" accept="image/jpeg,image/png,image/webp"><div class="form-text">JPG, PNG, or WEBP, maximum 5 MB. @if($package->image_path)Current image path: {{ $package->image_path }}@endif</div></div>
    <div class="col-12 d-flex gap-2 mt-4"><button class="btn btn-forest" type="submit">{{ $package->exists ? 'Save changes' : 'Create package' }}</button><a class="btn btn-outline-dark" href="{{ route('staff.packages.index') }}">Cancel</a></div>
</div></form></div></section>
@endsection