@extends('layouts.app')
@section('title', 'Book '.$tourPackage->name)
@section('content')
<section class="page-header"><div class="container-xl"><a class="text-decoration-none small" href="{{ route('packages.show', $tourPackage) }}"><i class="bi bi-arrow-left me-1"></i>Back to package</a><div class="eyebrow mt-3">Make it a trip</div><h1 class="display-type mt-2">Book {{ $tourPackage->name }}</h1></div></section>
<section class="py-4"><div class="container-xl"><form method="POST" action="{{ route('customer.bookings.store', $tourPackage) }}" data-booking-form>@csrf<div class="row g-4"><div class="col-lg-8">
    <div class="card-clean p-4 mb-4"><div class="booking-step"><div class="eyebrow">Step 1</div><h2 class="h4 mt-1">Choose your travel date</h2></div><div class="mt-3"><label class="form-label" for="travel_date">Travel date</label><input class="form-control" type="date" id="travel_date" name="travel_date" min="{{ max(today()->toDateString(), $tourPackage->start_date?->toDateString() ?? today()->toDateString()) }}" @if($tourPackage->end_date) max="{{ $tourPackage->end_date->toDateString() }}" @endif value="{{ old('travel_date', $tourPackage->start_date?->toDateString()) }}" required></div></div>
    <div class="card-clean p-4 mb-4"><div class="d-flex flex-wrap align-items-start justify-content-between gap-3"><div class="booking-step"><div class="eyebrow">Step 2</div><h2 class="h4 mt-1">Who’s coming along?</h2><p class="text-muted-custom mb-0">{{ $tourPackage->available_slots }} seats are currently available.</p></div><button class="btn btn-outline-forest btn-sm" type="button" data-add-traveler data-max="{{ $tourPackage->available_slots }}"><i class="bi bi-person-plus me-1"></i>Add traveler</button></div>
        <div class="vstack gap-3 mt-4" data-traveler-list><div class="traveler-row" data-traveler><div class="d-flex justify-content-between mb-3"><strong data-traveler-title>Traveler 1</strong></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Full name</label><input class="form-control" name="travelers[0][full_name]" required maxlength="200"></div><div class="col-md-6"><label class="form-label">Date of birth</label><input class="form-control" type="date" name="travelers[0][date_of_birth]" max="{{ today()->toDateString() }}"></div><div class="col-md-6"><label class="form-label">Contact number</label><input class="form-control" name="travelers[0][contact_number]" maxlength="30"></div><div class="col-md-6"><label class="form-label">Emergency contact</label><input class="form-control" name="travelers[0][emergency_contact]" maxlength="200"></div><div class="col-md-6"><label class="form-label">Emergency contact number</label><input class="form-control" name="travelers[0][emergency_contact_number]" maxlength="30"></div><div class="col-md-6"><label class="form-label">Address</label><input class="form-control" name="travelers[0][address]" maxlength="1000"></div></div></div></div>
        <template id="traveler-template"><div class="traveler-row" data-traveler><div class="d-flex justify-content-between mb-3"><strong data-traveler-title>Traveler</strong><button class="btn btn-sm btn-outline-danger" type="button" data-remove-traveler aria-label="Remove traveler"><i class="bi bi-trash"></i></button></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Full name</label><input class="form-control" data-field name="travelers[__INDEX__][full_name]" required maxlength="200"></div><div class="col-md-6"><label class="form-label">Date of birth</label><input class="form-control" data-field type="date" name="travelers[__INDEX__][date_of_birth]" max="{{ today()->toDateString() }}"></div><div class="col-md-6"><label class="form-label">Contact number</label><input class="form-control" data-field name="travelers[__INDEX__][contact_number]" maxlength="30"></div><div class="col-md-6"><label class="form-label">Emergency contact</label><input class="form-control" data-field name="travelers[__INDEX__][emergency_contact]" maxlength="200"></div><div class="col-md-6"><label class="form-label">Emergency contact number</label><input class="form-control" data-field name="travelers[__INDEX__][emergency_contact_number]" maxlength="30"></div><div class="col-md-6"><label class="form-label">Address</label><input class="form-control" data-field name="travelers[__INDEX__][address]" maxlength="1000"></div></div></div></template>
    </div>
    <div class="card-clean p-4"><div class="booking-step"><div class="eyebrow">Step 3</div><h2 class="h4 mt-1">Anything we should know?</h2></div><textarea class="form-control mt-3" name="customer_notes" rows="3" maxlength="2000" placeholder="Optional notes for the Travexgo team">{{ old('customer_notes') }}</textarea></div>
</div><aside class="col-lg-4"><div class="card-clean p-4 position-sticky" style="top:100px"><div class="eyebrow">Booking summary</div><h2 class="h4 mt-2">{{ $tourPackage->name }}</h2><div class="text-muted-custom">{{ $tourPackage->destination->name }} · {{ $tourPackage->duration_days }} days</div><hr><div class="d-flex justify-content-between"><span>Price per traveler</span><strong>₱{{ number_format((float) $tourPackage->price_per_person, 2) }}</strong></div><div class="d-flex justify-content-between mt-2"><span>Travelers</span><strong data-traveler-count>1</strong></div><div class="d-flex justify-content-between mt-3 pt-3 border-top"><strong>Estimated total</strong><strong class="package-price" data-booking-total data-price="{{ $tourPackage->price_per_person }}">₱{{ number_format((float) $tourPackage->price_per_person, 2) }}</strong></div><p class="small text-muted-custom mt-3">Final total is calculated and verified by the server. No payment is charged at this step.</p><button class="btn btn-coral w-100" type="submit">Confirm booking <i class="bi bi-arrow-right ms-1"></i></button></div></aside></div></form></div></section>
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const list=document.querySelector('[data-traveler-list]');const count=document.querySelector('[data-traveler-count]');const total=document.querySelector('[data-booking-total]');const update=()=>{const travelers=list?.querySelectorAll('[data-traveler]').length||0;if(count)count.textContent=String(travelers);if(total)total.textContent=new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(total.dataset.price)*travelers);document.querySelectorAll('[data-traveler-title]').forEach((title,index)=>title.textContent=`Traveler ${index+1}`)};document.addEventListener('click',(event)=>{if(event.target.closest('[data-add-traveler],[data-remove-traveler]'))setTimeout(update,0)});update()});</script>@endpush
@endsection