@extends('layouts.app')
@section('title', $tourPackage->name)
@section('content')
<section class="page-header"><div class="container-xl"><a class="text-decoration-none small" href="{{ route('packages.index') }}"><i class="bi bi-arrow-left me-1"></i>All packages</a><div class="row align-items-end g-3 mt-1"><div class="col-lg-8"><div class="eyebrow">{{ $tourPackage->destination->name }} · {{ $tourPackage->duration_days }} days / {{ $tourPackage->duration_nights }} nights</div><h1 class="display-type mt-2 mb-0">{{ $tourPackage->name }}</h1></div><div class="col-lg-4 text-lg-end"><span class="package-price fs-4">₱{{ number_format((float) $tourPackage->price_per_person, 2) }}</span><span class="text-muted-custom"> / person</span></div></div></div></section>
<section class="section-pad pt-4"><div class="container-xl"><div class="row g-4"><div class="col-lg-8">
    <img class="w-100 rounded-1 mb-4" style="aspect-ratio:16/8;object-fit:cover" src="{{ $tourPackage->image_path ? rtrim(config('services.supabase.url'), '/').'/storage/v1/object/public/'.config('services.supabase.buckets.tour_packages').'/'.$tourPackage->image_path : 'https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=1400&q=85' }}" alt="{{ $tourPackage->name }}">
    <h2 class="h4">The trip</h2><p class="text-muted-custom">{{ $tourPackage->description }}</p>
    <div class="row g-3 my-3"><div class="col-sm-6"><div class="card-clean p-3"><div class="eyebrow">Getting there</div><strong>{{ $tourPackage->transportation ?: 'Details provided after booking' }}</strong></div></div><div class="col-sm-6"><div class="card-clean p-3"><div class="eyebrow">Stay</div><strong>{{ $tourPackage->accommodation ?: 'Details provided after booking' }}</strong></div></div></div>
    <div class="row g-4"><div class="col-md-6"><h3 class="h5">Included</h3><ul class="text-muted-custom">@forelse($tourPackage->inclusions ?? [] as $item)<li>{{ $item }}</li>@empty<li>Ask us for package inclusions.</li>@endforelse</ul></div><div class="col-md-6"><h3 class="h5">Not included</h3><ul class="text-muted-custom">@forelse($tourPackage->exclusions ?? [] as $item)<li>{{ $item }}</li>@empty<li>Confirm exclusions with Travexgo.</li>@endforelse</ul></div></div>
    <h2 class="h4 mt-4">Itinerary</h2>@forelse($tourPackage->itineraries->groupBy('day_number') as $day => $items)<div class="card-clean p-3 mb-3"><div class="eyebrow">Day {{ $day }}</div>@foreach($items as $item)<div class="d-flex gap-3 py-2 border-bottom"><span class="text-muted-custom text-nowrap">{{ $item->activity_time ? substr((string) $item->activity_time, 0, 5) : '—' }}</span><div><strong>{{ $item->activity }}</strong>@if($item->location)<div class="small text-muted-custom">{{ $item->location }}</div>@endif@if($item->description)<div class="small text-muted-custom">{{ $item->description }}</div>@endif</div></div>@endforeach</div>@empty<p class="text-muted-custom">The detailed itinerary will be available soon.</p>@endforelse
</div><aside class="col-lg-4"><div class="card-clean p-4 position-sticky" style="top:100px"><div class="eyebrow">Your journey</div><h2 class="h4 mt-2">{{ $tourPackage->name }}</h2><div class="d-flex justify-content-between py-3 border-bottom"><span class="text-muted-custom">Price per person</span><strong>₱{{ number_format((float) $tourPackage->price_per_person, 2) }}</strong></div><div class="d-flex justify-content-between py-3 border-bottom"><span class="text-muted-custom">Available seats</span><strong>{{ $tourPackage->available_slots }}</strong></div><div class="d-flex justify-content-between py-3 border-bottom"><span class="text-muted-custom">Booking by</span><strong>{{ $tourPackage->booking_deadline?->format('M j, Y') ?? 'While seats last' }}</strong></div>
    @if($tourPackage->available_slots > 0)<a class="btn btn-coral w-100 mt-3" href="{{ auth()->check() && auth()->user()->role === 'customer' ? route('customer.bookings.create', $tourPackage) : route('login') }}">Book this trip <i class="bi bi-arrow-right ms-1"></i></a>@else<button class="btn btn-secondary w-100 mt-3" disabled>Fully booked</button>@endif
    <p class="small text-muted-custom mt-3 mb-0">No real payment is collected online. Payment submissions are reviewed by Travexgo staff.</p></div></aside></div></div></section>
@endsection